export type Errors =
  | 'PERMISSIONS_NOT_SUFFICIENT'
  | 'INVALID_HASH_SIGNATURE'
  | 'RESPONSE_TIMEOUT'
  | 'TIMEOUT'
  | 'ACTION_BLOCKED'
  | 'ACTION_LIMIT_EXCEEDED'
  | 'REQUEST_TIMESTAMP_TOO_OLD'
  | 'UNDER_MAINTENANCE'
